/**
 * Global theme palettes. Use THEMES[themeKey] and ensure every UI uses
 * theme.* so the app responds to light / normal / dark.
 */
export const THEMES = {
  light: {
    mode: 'light',
    background: '#F9FAFB',
    screenBackground: '#F9FAFB',
    navBarBackground: '#FFFFFF',
    surface: '#FFFFFF',
    surfaceAlt: '#F3F4F6',
    text: '#111827',
    textMuted: '#6B7280',
    accent: '#2563EB',
    accentAlt: '#10B981',
    success: '#34D399',
    danger: '#DC2626',
    error: '#DC2626',
    border: '#E5E7EB',
    gridLine: 'rgba(148, 163, 184, 0.4)',
    shadow: '#111827',
    holderBackground: '#E5E7EB',
    paperTexture: '#F3F4F6',
    buttonBg: '#2563EB',
    buttonText: '#FFFFFF',
    white: '#FFFFFF',
    pastelGreen: '#6EE7B7',
    pastelBlue: '#3B82F6',
    pastelBlueLight: '#60A5FA',
    accentLight: '#60A5FA',
    softHighlight: '#EFF6FF',
  },
  dark: {
    mode: 'dark',
    background: '#0a0a0f',
    screenBackground: '#0a0a0f',
    navBarBackground: '#15151f',
    surface: '#0a0a0f',
    surfaceAlt: '#15151f',
    text: '#F1F5F9',
    textMuted: '#94A3B8',
    accent: '#38BDF8',
    accentAlt: '#4ADE80',
    success: '#86EFAC',
    danger: '#F97373',
    error: '#F97373',
    border: '#1e1e2e',
    gridLine: 'rgba(148, 163, 184, 0.35)',
    shadow: '#000000',
    holderBackground: '#15151f',
    paperTexture: '#0a0a0f',
    buttonBg: '#38BDF8',
    buttonText: '#020617',
    white: '#FFFFFF',
    pastelGreen: '#86EFAC',
    pastelBlue: '#38BDF8',
    pastelBlueLight: '#7DD3FC',
    accentLight: '#7DD3FC',
    softHighlight: '#15151f',
  },
  normal: {
    mode: 'normal',
    background: '#E0F2FE',
    screenBackground: '#E0F2FE',
    navBarBackground: '#ECFDF5',
    surface: '#ECFDF5',
    surfaceAlt: '#DBEAFE',
    text: '#1F2933',
    textMuted: '#6B7280',
    accent: '#38BDF8',
    accentAlt: '#34D399',
    success: '#34D399',
    danger: '#F97373',
    error: '#F97373',
    border: '#BFDBFE',
    gridLine: 'rgba(129, 140, 248, 0.45)',
    shadow: '#1F2933',
    holderBackground: '#CCFBF1',
    paperTexture: '#DBEAFE',
    buttonBg: '#38BDF8',
    buttonText: '#FFFFFF',
    white: '#FFFFFF',
    pastelGreen: '#6EE7B7',
    pastelBlue: '#38BDF8',
    pastelBlueLight: '#7DD3FC',
    accentLight: '#7DD3FC',
    softHighlight: '#EFF6FF',
  },
};

export const DEFAULT_THEME_KEY = 'normal';

/** @deprecated Use THEMES[themeKey] or theme from context. Kept for one-off fallbacks only. */
export const COLORS = THEMES[DEFAULT_THEME_KEY];
